### ISSUE TITLE
升级12.2蓝牙问题

### ISSUE THREAD

**Issue by archo0ps** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#10]
从系统里面直升12.2后蓝牙找不到设备了，12.1里匹配的设备也是变灰色
![pic](https://user-images.githubusercontent.com/61302110/158056749-b1912ad2-26ba-4755-a6b3-5d6b044f292c.png)

是不是要重新做个系统U盘重装

**Comment by archo0ps** [comment]
![pic2](https://user-images.githubusercontent.com/61302110/158057286-f5974bb4-e9a3-498e-966e-9a14b0fa8264.png)
![pic3](https://user-images.githubusercontent.com/61302110/158057592-94557f90-04fd-4aee-9735-d115a42a4475.png)

**Comment by 0x676e67** [comment]
断开删掉设备 重新连，不行就重新替换EFI，使用最新版那个upgrade

**Comment by archo0ps** [comment]
> 断开删掉设备 重新连，不行就重新替换EFI，使用最新版那个upgrade

已经替换过了，蓝牙设备里加载不出来

**Comment by archo0ps** [comment]
用核显的问题，加了张显卡解决了。。

**Comment by 0x676e67** [comment]
> 用核显的问题，加了张显卡解决了。。

跟核显有啥关系

**Comment by archo0ps** [comment]
> 

不知道，加了张显卡就能用了，用核显 直接更新 和 U盘安装蓝牙都有问题
