### ISSUE TITLE
睡眠唤醒以后可能会出现无网络的情况

### ISSUE THREAD

**Issue by snailhd** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#11]
大佬，睡眠唤醒以后可能会出现自带网卡无网络的情况，能解决吗？每次都要去高级里面改配置才会有网

**Comment by 0x676e67** [comment]
> 大佬，睡眠唤醒以后可能会出现自带网卡无网络的情况，能解决吗？每次都要去高级里面改配置才会有网

是WiFi网卡还是网口。睡眠多久。

**Comment by snailhd** [comment]
网口，设置的定时睡眠，晚上1点睡眠到8点启动。有时候会出现无网络。

**Comment by 0x676e67** [comment]
> 网口，设置的定时睡眠，晚上1点睡眠到8点启动。有时候会出现无网络。

你更新8.0版本efi看看
