### ISSUE TITLE
请问如何删除独显缓冲帧? 前置雷电三的接口无法使用,请问该如何做?

### ISSUE THREAD

**Issue by beyond-infra** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#12]

**Comment by beyond-infra** [comment]
我没有独显, 经常使用移动硬盘,机箱后面的雷电口使用不方便,想使用主板扩展的雷电口. 请问大佬能否解答一下?

**Comment by 0x676e67** [comment]
config-extend-typec.plist这份配置支持前置主板拓展的前置typec口

**Comment by 0x676e67** [comment]
使用核显 独显配置删不删应该都没影响

**Comment by beyond-infra** [comment]
> config-extend-typec.plist这份配置支持前置主板拓展的前置typec口

谢谢大佬, 解决了
