### ISSUE TITLE
兄弟，可以搞个0.8.7版本OC的吗？

### ISSUE THREAD

**Issue by zhanggx** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#14]
13.1的镜像要求0.8.7版本OC了，兄弟能不能搞一个？
macOS Ventura 13.1 (22C65) With OpenCore 0.8.7 and winPE.dmg

**Comment by gngpp** [comment]
> 

明天搞

**Comment by 0x676e67** [comment]
> 13.1的镜像要求0.8.7版本OC了，兄弟能不能搞一个？ macOS Ventura 13.1 (22C65) With OpenCore 0.8.7 and winPE.dmg

明天搞

**Comment by 0x676e67** [comment]
release 0.8.8: https://github.com/gngpp/MSI-MEG-Z490I-Unify-Hackintosh-EFI/releases/tag/OC-0.8.8
