### ISSUE TITLE
怎么我装上去用不了啊？

### ISSUE THREAD

**Issue by chenzork** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#15]
我搞了个Mac os 13.2懒人版三分区镜像，换上了你的efi之后啰嗦模式报错进不去，配置区别可能就是我用的是核显，不知道是不是这个原因，config应该怎么改啊？求大神指导。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by 0x676e67** [comment]
因为没有更新，0.8.8是不支持13.2的，现在更新了 https://github.com/gngpp/MSI-MEG-Z490I-Unify-Hackintosh-EFI/releases/tag/OC-0.9.0

**Comment by 0x676e67** [comment]
> 我搞了个Mac os 13.2懒人版三分区镜像，换上了你的efi之后啰嗦模式报错进不去，配置区别可能就是我用的是核显，不知道是不是这个原因，config应该怎么改啊？求大神指导。
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

如果你是核显，这个删掉就行了
![image](https://user-images.githubusercontent.com/51810656/229001231-cee2c3d1-3018-46ea-9007-404bdd673e52.png)

**Comment by chenzork** [comment]
好的，谢谢大神！
