### ISSUE TITLE
关于wifi模块的问题

### ISSUE THREAD

**Issue by huiyi9420** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#5]
请教一下，替换网卡的方案是牺牲一个M.2来实现，还是直接更换AX201为其他网卡
我看到这样的描述，他这个我没能理解，难不成白果卡直接转接连接原来的AX201卡插槽就能识别
[WIFI/BT: BCM94352HMB + M.2 Key_B to minipcie](https://github.com/kingwood77/MSI-Z490i-Unify-Hackintosh)
在另一个论坛发现一位国外老哥是牺牲了一个m.2使用转接卡实现的
https://www.insanelymac.com/forum/topic/345970-guide-msi-meg-z490i-unify
想请教一下，建议使用那种解决方案，我本人已经测试过直接把AX201拆了，替换成BCM94360Z4无法正常识别

**Comment by 0x676e67** [comment]
msi z490i Wi-Fi网卡是cnvi，不可更换。z490i这代只有华擎的z490i幻影网卡是可拆卸更换的，但是如果你愿意牺牲m.2转接来插白果卡，也是没问题的，白果卡功能上更加完美。

**Comment by 0x676e67** [comment]
看需求，如果你想拥有更完美网卡功能，那就牺牲一个m.2接口转接网卡。如果只需求上网功能、隔空投放的话，那就不用更换网卡了，当然ax201蓝牙有点弱

**Comment by huiyi9420** [comment]
> msi z490i Wi-Fi网卡是cnvi，不可更换。z490i这代只有华擎的z490i幻影网卡是可拆卸更换的，但是如果你愿意牺牲m.2转接来插白果卡，也是没问题的，白果卡功能上更加完美。

我打算牺牲主板背面的M.2插槽来转接白果卡，我就是好奇github里有一位开源的说M.2Key_B to minipcie是个啥玩意。淘宝查了下，看起来就是一个minipcie转白果卡的板子，这玩意难道是插在了pcie x16的插槽上，看他还有显卡呢，咋实现的

**Comment by huiyi9420** [comment]
> 看需求，如果你想拥有更完美网卡功能，那就牺牲一个m.2接口转接网卡。如果只需求上网功能、隔空投放的话，那就不用更换网卡了，当然ax201蓝牙有点弱

我还没正常驱动这块AX201网卡，可能是我这边操作的问题，我正在尝试更换新的EFI

**Comment by 0x676e67** [comment]
> > msi z490i Wi-Fi网卡是cnvi，不可更换。z490i这代只有华擎的z490i幻影网卡是可拆卸更换的，但是如果你愿意牺牲m.2转接来插白果卡，也是没问题的，白果卡功能上更加完美。
> 
> 我打算牺牲主板背面的M.2插槽来转接白果卡，我就是好奇github里有一位开源的说M.2Key_B to minipcie是个啥玩意。淘宝查了下，看起来就是一个minipcie转白果卡的板子，这玩意难道是插在了pcie x16的插槽上，看他还有显卡呢，咋实现的

这玩意就是m2转插网卡的啊，笔记本就有这种类似转接板

**Comment by 0x676e67** [comment]
> > > msi z490i Wi-Fi网卡是cnvi，不可更换。z490i这代只有华擎的z490i幻影网卡是可拆卸更换的，但是如果你愿意牺牲m.2转接来插白果卡，也是没问题的，白果卡功能上更加完美。
> > 
> > 我打算牺牲主板背面的M.2插槽来转接白果卡，我就是好奇github里有一位开源的说M.2Key_B to minipcie是个啥玩意。淘宝查了下，看起来就是一个minipcie转白果卡的板子，这玩意难道是插在了pcie x16的插槽上，看他还有显卡呢，咋实现的
> 
> 这玩意就是m2转插网卡的啊，笔记本就有这种类似转接板

m.2也会占4条通道的 可以转mini pcie插槽

**Comment by 0x676e67** [comment]
> > 看需求，如果你想拥有更完美网卡功能，那就牺牲一个m.2接口转接网卡。如果只需求上网功能、隔空投放的话，那就不用更换网卡了，当然ax201蓝牙有点弱
> 
> 我还没正常驱动这块AX201网卡，可能是我这边操作的问题，我正在尝试更换新的EFI

你BIOS cnvi开了没有 不会禁用了吧？

**Comment by huiyi9420** [comment]
已经解决了，感谢🙏
