### ISSUE TITLE
相同主板i7-10700+6600XT黑屏

### ISSUE THREAD

**Issue by huiyi9420** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#6]
配置
主板:msi-z490i unify
CPU:i7-10700
内存:威刚D50 32*2
显卡:蓝宝石6600XT超白金
电源:联力SP750
机箱:超频三蜂鸟i100 Pro
按说明设置BIOS后，使用0.76版本的EFI引导黑屏，跑代码大概不到3秒钟左右黑屏，显示器一直无信号，有信号，无信号，有信号，就是没画面

**Comment by 0x676e67** [comment]
6600xt你可以去看看怎么驱动的 ，我这个自带有5500xt缓冲帧，建议删掉试试

**Comment by huiyi9420** [comment]
12.1系统
6600XT它是免驱的
只是需要增加agdpmod=pikera参数防止黑屏好像

**Comment by huiyi9420** [comment]
如果可能的话，可以截图一下告知我如何清除5500XT缓冲区么

**Comment by huiyi9420** [comment]
我是不是应该把config.plist内从223行到257行都删了，就行了

**Comment by huiyi9420** [comment]
尝试移除上述内容，启动跑代码后黑屏大约5秒左右可以显示输出了
