### ISSUE TITLE
i910900es qtb1 先装win10 后用easyuefi添加EFI 只有Windows选项

### ISSUE THREAD

**Issue by archo0ps** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#7]
如题

**Comment by archo0ps** [comment]
主板是一样的

**Comment by 0x676e67** [comment]
dg分区工具看看macos系统的分区，我不确定是不是你系统没了，如果引导能引导安装镜像进去是没有问题的

**Comment by archo0ps** [comment]
在DG下面是有HFS+的分区，插了在mbp下制作的U盘引导也不显示。。

**Comment by 0x676e67** [comment]
建议你单独把macos的efi放一个分区，Windows的efi也是单独一个分区，不要用什么easyefi那个东西，容易出问题

**Comment by 0x676e67** [comment]
EFI分区会创建吧？dg分个500m 把引导丢进去就行了

**Comment by archo0ps** [comment]
好的，我试试

**Comment by archo0ps** [comment]
我尝试了使用dg来添加引导，还是只显示一个Windows....

**Comment by 0x676e67** [comment]
你写的镜像有问题

**Comment by 0x676e67** [comment]
用etcher写系统镜像到u盘

**Comment by archo0ps** [comment]
我试试

**Comment by archo0ps** [comment]
现在是用etcher写了个mac的recovery进U盘，有个mac basic system的选项 进recovery 苹果logo读完条之后就自动进windows了...

**Comment by 0x676e67** [comment]
> 现在是用etcher写了个mac的recovery进U盘，有个mac basic system的选项 进recovery 苹果logo读完条之后就自动进windows了...

不晓得你怎么搞，建议全盘格式化先装macos，不懂的可以blibli搜索装黑苹果别人怎么装的，还有这个引导是带5500xt缓冲帧的，如果你不是用这张卡独显，那么要去掉。

**Comment by archo0ps** [comment]
现在用的是核显，用白果写镜像到U盘，然后用DG复制EFI到ESP分区，添加bootx64.efi的启动项，插U盘装系统，流程大概是这样吧？

**Comment by 0x676e67** [comment]
> 现在用的是核显，用白果写镜像到U盘，然后用DG复制EFI到ESP分区，添加bootx64.efi的启动项，插U盘装系统，流程大概是这样吧？

ESP分区里什么都要删掉，然后把我的引导社efi扔进去就行了，不要动其他的，重启选oc 启动 选择进去u盘镜像

**Comment by archo0ps** [comment]
先装Mac解决了...，谢谢
