### ISSUE TITLE
声音有噪音的问题

### ISSUE THREAD

**Issue by archo0ps** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#8]
连接AirPods pro 久了会有电流音，显示器LG UP850 不能外放声音，不知道你有没有遇到过。

**Comment by 0x676e67** [comment]
> 连接AirPods pro 久了会有电流音，显示器LG UP850 不能外放声音，不知道你有没有遇到过。

更新了驱动，下载最新版efi试试：https://github.com/zf1976/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI/releases/tag/OC-0.7.6

**Comment by archo0ps** [comment]
> > 连接AirPods pro 久了会有电流音，显示器LG UP850 不能外放声音，不知道你有没有遇到过。
> 
> 更新了驱动，下载最新版efi试试：https://github.com/zf1976/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI/releases/tag/OC-0.7.6

替换了之后改善很多，本来连耳机有时能用有时滋滋滋的声音很大，我还以为是主板的耳机接口出问题了😅，现在还是会有一点点滋滋滋的电流声。
AirPods 是完全没有噪音的，就是在看直播的时候有概率会出现断断续续的声音和电流声，我在试试还会不会出现这种情况。

**Comment by archo0ps** [comment]
刚才试了下，连接AirPods 打开qq音乐，然后开一个视频，15分钟左右就开始出现电流声，声音开始卡顿，再然后就没声音了。
而且在切换回耳机就又出现很大的噪音了，再过一段时间使用耳机又正常了，只有轻微的电流声。

**Comment by 0x676e67** [comment]
> > > 连接AirPods pro 久了会有电流音，显示器LG UP850 不能外放声音，不知道你有没有遇到过。
> > 
> > 更新了驱动，下载最新版efi试试：https://github.com/zf1976/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI/releases/tag/OC-0.7.6
> 
> 替换了之后改善很多，本来连耳机有时能用有时滋滋滋的声音很大，我还以为是主板的耳机接口出问题了😅，现在还是会有一点点滋滋滋的电流声。
> AirPods 是完全没有噪音的，就是在看直播的时候有概率会出现断断续续的声音和电流声，我在试试还会不会出现这种情况。

你其他系统主板🎧有没有影响，我这边一点问题没有

**Comment by archo0ps** [comment]
> 

那我试下重装

**Comment by archo0ps** [comment]
测试过了，在Win10下也存在，感觉是主板的问题了

**Comment by 0x676e67** [comment]
> 测试过了，在Win10下也存在，感觉是主板的问题了

烧主板了，送售后吧，我主板昨天才回来

**Comment by archo0ps** [comment]
😓，应该是了，核显输出声音到显示器一点问题也没有。

**Comment by archo0ps** [comment]
没想到最后是CPU的问题。。
