### ISSUE TITLE
HDMI/DP 没有声音输出

### ISSUE THREAD

**Issue by Raneee** [gngpp/MSI-MEG-Z490I-Unify-Hackintosh-OC-EFI#9]
能不能看看EFI怎么修改能HDMI/DP输出音频，其它都已经完美了（隔空投送好像不能用）

**Comment by 0x676e67** [comment]
> 能不能看看EFI怎么修改能HDMI/DP输出音频，其它都已经完美了（隔空投送好像不能用）

DP接口显示器可以输出音频，HDMI无解，隔空也无解，除非换白果卡

**Comment by Raneee** [comment]
EFI需要修改什么吗？我的DP没有声音哎

**Comment by Raneee** [comment]
对了，我是核显DP没有声音，我的配置没有独显

**Comment by 0x676e67** [comment]
目前核显声音无解，要么不显示要么显示没有声音。暂时没有找到办法，隔壁家的efi连核显都点不亮呢

**Comment by Raneee** [comment]
对，感谢！我也是试过很多后就这个最完美！

**Comment by 0x676e67** [comment]
> 对，感谢！我也是试过很多后就这个最完美！

显示器音频用处不大，你还不如插主板上的就行了

**Comment by 0x676e67** [comment]
> 对了，我是核显DP没有声音，我的配置没有独显

核显hdmi 音频输出到屏幕修复，更新0.8.1版本试试，看看dp能不能用
